### ISSUE TITLE
issue with connection maybe

### ISSUE THREAD

**Issue by LeakorgX** [rohiitq/webRtcProject#5]
error connecting db RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received type string ('ur redis port').
    at lookupAndConnect (node:net:1301:5)
    at Socket.connect (node:net:1258:5)
    at Object.connect (node:net:242:17)
    at RedisSocket._RedisSocket_createNetSocket (D:\Users\Administrator\Desktop\omegleMeet-main\server\node_modules\@redis\client\dist\lib\client\socket.js:208:21)
    at D:\Users\Administrator\Desktop\omegleMeet-main\server\node_modules\@redis\client\dist\lib\client\socket.js:175:101
    at new Promise (<anonymous>)
    at RedisSocket._RedisSocket_createSocket (D:\Users\Administrator\Desktop\omegleMeet-main\server\node_modules\@redis\client\dist\lib\client\socket.js:172:12)
    at RedisSocket._RedisSocket_connect (D:\Users\Administrator\Desktop\omegleMeet-main\server\node_modules\@redis\client\dist\lib\client\socket.js:147:154)
    at RedisSocket.connect (D:\Users\Administrator\Desktop\omegleMeet-main\server\node_modules\@redis\client\dist\lib\client\socket.js:51:96)
    at Commander.connect (D:\Users\Administrator\Desktop\omegleMeet-main\server\node_modules\@redis\client\dist\lib\client\index.js:185:70) {
  code: 'ERR_SOCKET_BAD_PORT'
}
port running at 3000

**Comment by rohitsx** [comment]
you need to fill this values on .env
REDIS_PWD="ur redis password"
REDIS_HOST="ur redis host"
REDIS_PORT="ur redis port"
